name: Update Dojo

on: push

jobs:
  update:
    runs-on: self-hosted
    steps:
      - uses: pwncollege/dojo-update@v1
        with:
          dojo: example
          update_code: ${{ secrets.UPDATE_CODE }}
